# NumPy 

In [1]:
import numpy as np

## Creating NumPy Arrays from Objects

### From a Python List


In [2]:
l = [1,2,3]
l

[1, 2, 3]

In [3]:
np.array(l)

array([1, 2, 3])

In [4]:
m = [[1,2,3],[4,5,6],[7,8,9]]
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Number generators

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Random numbers
.rand -- uniform

.randn -- standard normal distribution

.randint -- integer from range

In [12]:
np.random.rand(2)


array([0.1331214 , 0.82237633])

In [13]:
np.random.rand(3,3)

array([[0.69681652, 0.89535774, 0.31319823],
       [0.75713898, 0.77162844, 0.50668227],
       [0.17080101, 0.56084306, 0.89368034]])

In [14]:
np.random.seed(42) #reproducability - same cell

## Attributes and Methods


In [15]:
a = np.arange(25)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [16]:
a.shape

(25,)

In [17]:
a.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [18]:
a.reshape(5,5).shape

(5, 5)

In [19]:
a.max()

48

In [20]:
a.argmax()

24

In [21]:
a.min()

0

In [22]:
a.argmin()

0

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.array([1.2, 3.4, 5.6])
b.dtype

dtype('float64')

# Indexing and Selection

In [25]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a[5]

5

In [27]:
a[1:5]

array([1, 2, 3, 4])

In [28]:
a[:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [29]:
a[1:5] = 100
a

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [30]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a_slice= a[0:6]
a_slice

array([0, 1, 2, 3, 4, 5])

In [33]:
a_slice[:]=99
a_slice

array([99, 99, 99, 99, 99, 99])

!!!!!! The changes also occur in our original array!

In [34]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
a_copy = a.copy()
a_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Matrices

In [36]:
a2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# Row
a2d[1]

array([4, 5, 6])

In [38]:
a2d[1,:]

array([4, 5, 6])

arr2d[row][col] or arr2d[row,col]

In [39]:
a2d[1][0]

4

In [40]:
a2d[1,0]

4

In [41]:
a2d[:2,:2]

array([[1, 2],
       [4, 5]])

# Conditional Selection

In [42]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
a_cond = a > 4
a_cond 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
a[a_cond]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
i = 4
a[a > i]

array([ 5,  6,  7,  8,  9, 10])

# Operations

In [48]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a + a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
a * a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [54]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
np.sqrt(a**2)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [56]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

##  Statistics

In [57]:
a.sum()

55

In [58]:
a.mean()

5.5

In [59]:
a.max()

10

In [60]:
a.std()

2.8722813232690143

In [61]:
a.var()

8.25

## Axes

In [62]:
a2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a2d.sum(axis=0)

array([15, 18, 21, 24])

In [64]:
a2d.sum(axis=1)

array([10, 26, 42])

In [65]:
a2d.shape

(3, 4)